spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jackson:
    serialization:
      write-dates-as-timestamps: false
server:
#  port: 443
  servlet:
    contextPath: /pa165
#  ssl:
#    key-store: classpath:keystore/keystore.p12
#    key-store-password: tomcat
#    key-store-type: PKCS12
#    key-alias: tomcat
